name: Build Binaries


on:
  push:
    branches:
      - '**'


jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false # do not stop all builds if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]


    steps:
    - uses: actions/checkout@v3
    - uses: julia-actions/setup-julia@v1
      with:
        version: 1.6

    - name: Run command on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        julia -e 'using Pkg; Pkg.add("SCIP")'
        du -sh ~/.julia/artifacts
