name: Build Binaries


on:
  push:
    branches:
      - '**'


jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false # do not stop all builds if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]


    steps:
    - uses: actions/checkout@v3
    - uses: julia-actions/setup-julia@v1
      with:
        version: 1.6

    - name: Run command on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        julia -e 'using Pkg; Pkg.add("SCIP")'

        cd ~/.julia/artifacts

        for dir in */; do  # Loop through all subdirectories
            # Skip 'lib', 'include', and 'bin' folders
            if [[ "$dir" == "lib/" || "$dir" == "include/" || "$dir" == "bin/" ]]; then
                continue
            fi

            # Copy all files from subdirectories to the parent directory
            sudo cp -r "$dir"* .
        done

        # ZIP include, lib and bin folders
        sudo zip -r include.zip include
        sudo zip -r lib.zip lib
        sudo zip -r bin.zip bin

    - uses: actions/upload-artifact@v3
      with:
        name: lib
        path: ~/.julia/artifacts/lib.zip
    
    - uses: actions/upload-artifact@v3
      with:
        name: include
        path: ~/.julia/artifacts/include.zip
    
    - uses: actions/upload-artifact@v3
      with:
        name: bin
        path: ~/.julia/artifacts/bin.zip


